<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>JWT Auth</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='/css/main.css' rel='stylesheet' type='text/css'>

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <!-- CSS -->
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/alertify.min.css"/>
        <!-- Default theme -->
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/themes/default.min.css"/>
        <!-- Semantic UI theme -->
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/themes/semantic.min.css"/>
        <!-- Bootstrap theme -->
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/themes/bootstrap.min.css"/>

        <!-- JS -->
        <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/alertify.min.js"></script>
    </head>
    <body>
    
        <div class="content">
            <h1>JWT Auth</h1>
            <div id="login">
                <form v-on:submit.prevent="login" id="loginForm" method="post" action="/api/auth">
                    <div class="form-group">
                      <label for="usr">Username:</label>
                      <input type="text" class="form-control" id="usr" v-model="username">
                    </div>
                    <div class="form-group">
                      <label for="pwd">Password:</label>
                      <input type="password" class="form-control" id="pwd" v-model="pwd">
                    </div>
                    
                    <input class="btn btn-primary" type="submit" value="Login (ask for JWT)" style="width: 100%;"> 
                </form>

                <p><span>If you change jwt, you will get a 401 Unauthorized. Try it if you want.</span></p>

                <textarea v-model="jwt" style="width: 100%;" rows="5"></textarea>
            </div>

            <div id="vueJwt" class="content">
                <button type="button" class="btn btn-primary" v-on:click="getUser" style="width: 100%;">Get User ID 1</button>    
                <div ref="jwt" id="vueJwtResult" style="width: 100%; margin: 10px; display: none;">
                    {{ vueJwtResult.id }} : {{ vueJwtResult.username }}
                </div>   
                <div ref="error" id="vueJwtError" style="width: 100%; margin: 10px; color: red;  display: none;">
                    {{ vueJwtError }}
                </div>   
            </div>
        </div> 

    </body>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-session@1.0.0/index.unpkg.js"></script>
    
    <script src="/js/login.js"></script>
    <script src="/js/api.js"></script>
</html>
